Change in the Fan Speed displaying....
Better to use percentage for fan speed as the original script unable to parse 60% fan speed (0x3c) and throws this error below:

  UPS PIco FAN Speed....:
Traceback (most recent call last):
  File "./pico_status.py", line 263, in <module>
    print " ","UPS PIco FAN Speed....:",fan_speed(),"RPM"
  File "./pico_status.py", line 201, in fan_speed
    return int (float(data) * 100)
ValueError: invalid literal for float(): 3c